export const ko_KR = {
  toolbarTips: {
    bold: '진하게',
    underline: '밑줄',
    italic: '기울임',
    strikeThrough: '취소선',
    title: '표제',
    sub: '아래 첨자',
    sup: '위 첨자',
    quote: '인용문',
    unorderedList: '글머리 기호',
    orderedList: '번호 매기기',
    task: '할 일 목록',
    codeRow: '인라인 코드',
    code: '코드 블록',
    link: '링크',
    image: '이미지',
    table: '테이블',
    mermaid: 'Mermaid',
    katex: 'Formular',
    revoke: '되돌리기',
    next: '다시 실행',
    save: '임시 저장',
    prettier: '정렬',
    pageFullscreen: '페이지 전체화면',
    fullscreen: '전체화면',
    preview: '미리보기',
    htmlPreview: 'HTML 미리보기',
    catalog: '카탈로그',
    github: ' Github 소스 코드',
  },
  titleItem: {
    h1: '1 Heading',
    h2: '2 Heading',
    h3: '3 Heading',
    h4: '4 Heading',
    h5: '5 Heading',
    h6: '6 Heading',
  },
  imgTitleItem: {
    link: '링크 추가',
    upload: '이미지 업로드',
    clip2upload: '클립 업로드',
  },
  linkModalTips: {
    title: '링크 추가',
    descLabel: '설명:',
    descLabelPlaceHolder: '(선택사항) 설명을 입력해 주세요...',
    urlLabel: '링크:',
    urlLabelPlaceHolder: '링크를 입력해 주세요...',
    buttonOK: '완료',
  },
  clipModalTips: {
    title: '클립 이미지 업로드',
    buttonUpload: '업로드',
  },
  copyCode: {
    text: '복사하기',
    successTips: '복사 완료!',
    failTips: '복사 실패...',
  },
  mermaid: {
    flow: 'flow',
    sequence: 'sequence',
    gantt: 'gantt',
    class: 'class',
    state: 'state',
    pie: 'pie',
    relationship: 'relationship',
    journey: 'journey',
  },
  katex: {
    inline: 'inline',
    block: 'block',
  },
  footer: {
    markdownTotal: '글자 수',
    scrollAuto: '자동 스크롤',
  },
}