export const KO_KR = {
  toolbarTips: {
    bold: 'bold',
    underline: 'underline',
    italic: 'italic',
    strikeThrough: 'strikeThrough',
    title: 'title',
    sub: 'subscript',
    sup: 'superscript',
    quote: 'quote',
    unorderedList: 'unordered list',
    orderedList: 'ordered list',
    task: 'task list',
    codeRow: 'inline code',
    code: 'block-level code',
    link: 'link',
    image: 'image',
    table: 'table',
    mermaid: 'mermaid',
    katex: 'formula',
    revoke: 'revoke',
    next: 'undo revoke',
    save: 'save',
    prettier: 'prettier',
    pageFullscreen: 'fullscreen in page',
    fullscreen: 'fullscreen',
    preview: 'preview',
    htmlPreview: 'html preview',
    catalog: 'catalog',
    github: 'source code',
  },
  titleItem: {
    h1: '1 Heading',
    h2: '2 Heading',
    h3: '3 Heading',
    h4: '4 Heading',
    h5: '5 Heading',
    h6: '6 Heading',
  },
  imgTitleItem: {
    link: '링크 추가',
    upload: '사진 업로드',
    clip2upload: '클립 업로드',
  },
  linkModalTips: {
    title: 'Add ',
    descLabel: 'Desc:',
    descLabelPlaceHolder: 'Enter a description...',
    urlLabel: 'Link:',
    urlLabelPlaceHolder: 'Enter a link...',
    buttonOK: 'OK',
  },
  clipModalTips: {
    title: 'Crop Image',
    buttonUpload: 'Upload',
  },
  copyCode: {
    text: 'Copy',
    successTips: 'Copied!',
    failTips: 'Copy failed!',
  },
  mermaid: {
    flow: 'flow',
    sequence: 'sequence',
    gantt: 'gantt',
    class: 'class',
    state: 'state',
    pie: 'pie',
    relationship: 'relationship',
    journey: 'journey',
  },
  katex: {
    inline: 'inline',
    block: 'block',
  },
  footer: {
    markdownTotal: '글자 수',
    scrollAuto: '자동 스크롤',
  },
}